name: Deploy Pygame to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install pygbag

      - name: Build with Pygbag
        run: pygbag .

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/web/* .
          git add .
          git commit -m "Automated deployment"
          git push -f origin gh-pages
